apiVersion: v1
kind: Pod
metadata:
  name: dblinkpg-pod
  annotations:
    io.podman.annotations.userns: keep-id
spec:
  containers:
    - name: postgres17
      image: docker.io/postgres:17
      ports:
        - containerPort: 5432
          hostPort: 57023
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: dblink_db
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretkeyRef:
              name: pg-secret
              key: POSTGRES_PASSWORD
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pgdat
  volumes:
    - name: pgdat
      persistentVolumeClaim:
        claimName: pgdata-dblink
